services:
  postgres:
    image: postgres:17
    container_name: hotel_booking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: yassirch
      POSTGRES_PASSWORD: yassir123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel-booking-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: yassir@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yassir123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: